name       : evolution
version    : 3.48.1
release    : 65
source     :
    - https://download.gnome.org/sources/evolution/3.48/evolution-3.48.1.tar.xz : b49a5adeedc91b1d3254f030f5a7df8e26182e3340cef77711ca1bf4553ee650
license    : LGPL-2.1-or-later
component  : network.mail
summary    : Evolution Mail Client
description: |
    Evolution Mail Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gweather4)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libcmark)
    - pkgconfig(libebackend-1.2)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(nss)
    - pkgconfig(shared-mime-info)
    - pkgconfig(webkit2gtk-4.1)
    - gtk-doc
    - highlight
    - itstool
    - openldap-devel
rundep     :
    - highlight
setup      : |
    %cmake_ninja \
        -DENABLE_AUTOAR=ON \
        -DENABLE_GTK_DOC=ON \
        -DENABLE_TEXT_HIGHLIGHT=ON \
        -DENABLE_PST_IMPORT=OFF \
        -DENABLE_YTNEF=OFF \
        -DLIB_INSTALL_DIR=%libdir% \
        -DSYSCONF_INSTALL_DIR=/etc \
        -DWITH_OPENLDAP=ON \
        -DWITH_GWEATHER4=ON \
        -DENABLE_WEATHER=ON .
build      : |
    %ninja_build
install    : |
    %ninja_install
