name       : evolution
version    : 3.18.4
release    : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution/3.18/evolution-3.18.4.tar.xz : 8161a0ebc77e61904dfaca9745595fefbf84d834a07ee1132d1f8d030dabfefb
license    : LGPL-2.1+
summary    : Evolution Mail Client
description: |
    Evolution Mail Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(libnotify)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libgdata)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(cryptui-0.0)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(libebackend-1.2)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libical)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(enchant)
    - pkgconfig(shared-mime-info)
    - pkgconfig(gsettings-desktop-schemas)
    - itstool
setup      : |
    %configure --disable-autoar --disable-text-highlight --disable-pst-import
build      : |
    %make
install    : |
    %make_install
