name       : evolution
version    : 3.20.5
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution/3.20/evolution-3.20.5.tar.xz : 2e13551ce0996963506f0bdde5e01c3b8aa0622849a272ff12877cd595baeb6e
license    : LGPL-2.1+
component  : network.mail
summary    : Evolution Mail Client
description: |
    Evolution Mail Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cryptui-0.0)
    - pkgconfig(enchant)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libebackend-1.2)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(shared-mime-info)
    - pkgconfig(webkitgtk-3.0)
    - itstool
setup      : |
    %configure --disable-autoar --disable-text-highlight --disable-pst-import
build      : |
    %make
install    : |
    %make_install
