name       : evolution
version    : 3.16.5
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution/3.16/evolution-3.16.5.tar.xz : fef4e8d0a81dc4562f984dddc5ccfee885506a2e030692b5ac6cd50e32efce37
license    :
    - LGPL-2.1+
summary    : Evolution Mail Client
description: |
    Evolution Mail Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libgdata)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(libebackend-1.2)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libical)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(enchant)
    - pkgconfig(shared-mime-info)
    - pkgconfig(gsettings-desktop-schemas)
    - itstool
setup      : |
    %configure --disable-autoar
build      : |
    %make
install    : |
    %make_install
