name       : evolution
version    : 3.44.0
release    : 58
source     :
    - https://download.gnome.org/sources/evolution/3.44/evolution-3.44.0.tar.xz : df21d3df5224dfa842ea290effcd902afd4b1418608a4dfb6907a3b7d4d994f9
license    : LGPL-2.1-or-later
component  : network.mail
summary    : Evolution Mail Client
description: |
    Evolution Mail Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gweather4)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libcmark)
    - pkgconfig(libebackend-1.2)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(nss)
    - pkgconfig(shared-mime-info)
    - pkgconfig(webkit2gtk-4.0)
    - gtk-doc
    - highlight
    - itstool
    - openldap-devel
rundep     :
    - highlight
setup      : |
    %cmake_ninja \
        -DENABLE_AUTOAR=ON \
        -DENABLE_GTK_DOC=ON \
        -DENABLE_TEXT_HIGHLIGHT=ON \
        -DENABLE_PST_IMPORT=OFF \
        -DENABLE_YTNEF=OFF \
        -DLIB_INSTALL_DIR=%libdir% \
        -DSYSCONF_INSTALL_DIR=/etc \
        -DWITH_OPENLDAP=ON \
        -DWITH_GWEATHER4=ON .
build      : |
    %ninja_build
install    : |
    %ninja_install
