name       : evolution
version    : 3.22.4
release    : 11
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution/3.22/evolution-3.22.4.tar.xz : 522209f022a468c9031fd393fe4ba6c655dedfa06dd6ae59d2d693d1485c690a
license    : LGPL-2.1+
component  : network.mail
summary    : Evolution Mail Client
description: |
    Evolution Mail Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cryptui-0.0)
    - pkgconfig(enchant)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libebackend-1.2)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(shared-mime-info)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %configure --disable-autoar --disable-text-highlight --disable-pst-import
build      : |
    %make
install    : |
    %make_install
