name       : evolution
version    : '3.40'
release    : 51
source     :
    - https://download.gnome.org/sources/evolution/3.40/evolution-3.40.0.tar.xz : 030a27b46c971835821c1b04d9023f9ff8f4113e1a411633dee403112033d51b
license    : LGPL-2.1-or-later
component  : network.mail
summary    : Evolution Mail Client
description: |
    Evolution Mail Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libebackend-1.2)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(shared-mime-info)
    - pkgconfig(webkit2gtk-4.0)
    - gtk-doc
    - highlight
    - itstool
    - openldap-devel
rundep     :
    - highlight
setup      : |
    %cmake \
        -DENABLE_AUTOAR=ON \
        -DENABLE_GTK_DOC=ON \
        -DENABLE_TEXT_HIGHLIGHT=ON \
        -DENABLE_PST_IMPORT=OFF \
        -DENABLE_YTNEF=OFF \
        -DLIB_INSTALL_DIR=%libdir% \
        -DSYSCONF_INSTALL_DIR=/etc \
        -DWITH_OPENLDAP=ON .
build      : |
    %make
install    : |
    %make_install
